- name : loop name
  hosts: all
  tasks: 
 - name : install packages
      become: true
      apt: 
        name: "{{item}}"
        state: latest
      loop:
        - httpd
        - tree
        - vsftpd
        